eurostat_inventory:
  - isoc_ske_itspen2
  - isoc_ske_itrcrn2
  - isoc_ske_fct
  - hrst_st_nfieocc
  - hrst_st_nsec2
  - isoc_ic_biper2
  - lfsa_egan2
  - educ_uoe_grad02
  - hrst_fl_tegrad
  - isoc_sks_itspt
  - isoc_ski_itemp
  - isoc_ske_ittn2